# context file for the web scraper and LLM

# the config settings for the news scraper
news:

  # The string to use to define what to search for:
  TOPIC: 'drone OR quadcopter OR hexacopter'

  # The language code to use
  LANGUAGE: 'en'

  # The country code to use
  COUNTRY: 'US'

  # How far back in time to look for articles EXAMPLE: 1h, 7d, 1m, 1y
  LOOKBACK: '1h'

# config settings for the LLM analyzer
llm:

  # Which model to use
  ID: 'llama3.2'

  # The context for what the model is supposed to do
  CONTEXT: 'Analyze the following news article and decide if it is about a drone incident in the US or not.  An incident is where people or property could or have already been hurt by drones or UAVs.  Return a JSON object with the results. The JSON object should contain the following fields:  "isIncident" (boolean), "confidence" (float), "location" (string).  The "isIncident" field should be true if the article is about a drone incident in the US and false otherwise.  The "confidence" field should be a float between 0 and 1 that represents the models confidence in its prediction.  The "location" field should be a string that represents the location of the story in a City, State format.  If the location is not in the United States, set the location to City, Country. Only return these fields.  Do not return anything other than the JSON object.'